/* NorthBridge site search index.
   Static and bilingual so search works instantly, offline, and with no request.
   Add a row whenever you add a page or a section worth finding. */
window.NB_SEARCH = [
  { url: 'index.html#brands', en: { section: 'NorthBridge', title: 'What we do', body: 'Four practices: Cinderella for data and workflows, Hermes for client communication, Socrates for AI training, and PerceptFolio for quantitative trading. Real estate is coming soon.' }, es: { section: 'NorthBridge', title: 'Qué hacemos', body: 'Cuatro prácticas: Cinderella para datos y flujos, Hermes para comunicación con clientes, Socrates para capacitación en IA, y PerceptFolio para trading cuantitativo. Bienes raíces muy pronto.' } },
  { url: 'index.html#plans', en: { section: 'NorthBridge', title: 'Plans and pricing', body: 'Bundles combining the practices: Starter $299/month, Growth $649/month, Scale $699/month. Individual plans from $99. 30-day money-back guarantee on your first month.' }, es: { section: 'NorthBridge', title: 'Planes y precios', body: 'Paquetes que combinan las prácticas: Inicial $299/mes, Crecimiento $649/mes, Escala $699/mes. Planes individuales desde $99. Garantía de devolución de 30 días en tu primer mes.' } },
  { url: 'index.html#process', en: { section: 'NorthBridge', title: 'The NorthBridge Cycle', body: 'Diagnose in two to three days, build in three to seven days, then educate and train your team in one session. Repeats quarterly.' }, es: { section: 'NorthBridge', title: 'El Ciclo NorthBridge', body: 'Diagnosticamos en dos o tres días, construimos en tres a siete días, y capacitamos a tu equipo en una sesión. Se repite cada trimestre.' } },
  { url: 'index.html#faq', en: { section: 'NorthBridge', title: 'Frequently asked questions', body: 'What happens after I email you, what counts as a workflow, will automated messages annoy my clients, what tools does this run on, how the money-back guarantee works, how much of my time setup takes.' }, es: { section: 'NorthBridge', title: 'Preguntas frecuentes', body: 'Qué pasa después de escribirles, qué cuenta como un flujo, si los mensajes automáticos molestan a mis clientes, con qué herramientas funciona, cómo funciona la garantía, cuánto tiempo toma la instalación.' } },

  { url: 'cinderella.html', en: { section: 'Cinderella', title: 'Data and workflow automation', body: 'Payment chasing, invoice reminders, automatic reports, data moved between your apps, client onboarding checklists. Built on n8n in an account you own. Plans: Sweep $199, Shine $329, Spotless $349 per month.' }, es: { section: 'Cinderella', title: 'Automatización de datos y flujos', body: 'Cobro de facturas, recordatorios de pago, reportes automáticos, datos movidos entre tus aplicaciones, altas de clientes. Construido en n8n en una cuenta tuya. Planes: Sweep $199, Shine $329, Spotless $349 al mes.' } },
  { url: 'hermes.html', en: { section: 'Hermes', title: 'AI client communication', body: 'Follow-up sequences that never forget a lead, instant AI messaging for common questions, AI voice agents for calls you cannot take. Plans: Courier $149, Herald $279, Wings $319 per month.' }, es: { section: 'Hermes', title: 'Comunicación con clientes con IA', body: 'Secuencias de seguimiento que nunca olvidan un prospecto, mensajería con IA que responde al instante, agentes de voz con IA para llamadas que no puedes atender. Planes: Courier $149, Herald $279, Wings $319 al mes.' } },
  { url: 'socrates.html', en: { section: 'Socrates', title: 'AI training and workshops', body: 'Hands-on AI fluency training for business teams, AI literacy for schools, and talks for events. Virtual anywhere, in person in Quito, English or Spanish. Plans: Foundations $99, Academy $199, Agora $249 per month.' }, es: { section: 'Socrates', title: 'Capacitación y talleres de IA', body: 'Capacitación práctica en IA para equipos, alfabetización en IA para escuelas, y charlas para eventos. Virtual donde estés, presencial en Quito, en inglés o español. Planes: Foundations $99, Academy $199, Agora $249 al mes.' } },

  { url: 'perceptfolio.html', en: { section: 'PerceptFolio', title: 'Quantitative trading terminal', body: 'PerceptFolio.com is the NorthBridge quant trading terminal: systematic research, backtesting, signal monitoring and portfolio analytics in one workspace. Not investment advice.' }, es: { section: 'PerceptFolio', title: 'Terminal de trading cuantitativo', body: 'PerceptFolio.com es la terminal de trading cuantitativo de NorthBridge: investigación sistemática, backtesting, monitoreo de señales y analítica de portafolio en un solo lugar. No es asesoría de inversión.' } },
  { url: 'perceptfolio.html#market', en: { section: 'PerceptFolio', title: 'Market — leaders by period', body: 'Best performing stocks over the last month, the last year and the last five years, ranked from the tracked universe. Past performance does not predict future returns.' }, es: { section: 'PerceptFolio', title: 'Mercado — líderes por periodo', body: 'Las acciones con mejor rendimiento del último mes, del último año y de los últimos cinco años, ordenadas dentro del universo seguido. El rendimiento pasado no predice retornos futuros.' } },
  { url: 'perceptfolio.html#terminal', en: { section: 'PerceptFolio', title: 'What the terminal does', body: 'Strategy research, vectorised backtests with transaction costs, live signal monitoring, risk and drawdown analytics, and exportable research notes.' }, es: { section: 'PerceptFolio', title: 'Qué hace la terminal', body: 'Investigación de estrategias, backtests vectorizados con costos de transacción, monitoreo de señales en vivo, analítica de riesgo y drawdown, y notas de investigación exportables.' } },

  { url: 'contact.html', en: { section: 'Contact', title: 'Contact NorthBridge or a branch', body: 'Send a message to NorthBridge, Cinderella, Hermes, Socrates, PerceptFolio or the real estate branch. Replies within one business day. Email northbridgeai1@gmail.com.' }, es: { section: 'Contacto', title: 'Contacta a NorthBridge o una rama', body: 'Envía un mensaje a NorthBridge, Cinderella, Hermes, Socrates, PerceptFolio o la rama de bienes raíces. Respondemos en un día hábil. Correo northbridgeai1@gmail.com.' } },
  { url: 'book.html', en: { section: 'Contact', title: 'Book a first meeting', body: 'Pick a time for a free 30-minute first meeting. Zoom or Google Meet, English or Spanish.' }, es: { section: 'Contacto', title: 'Agenda una primera reunión', body: 'Elige un horario para una primera reunión gratuita de 30 minutos. Zoom o Google Meet, en inglés o español.' } },
  { url: 'terms.html', en: { section: 'Legal', title: 'Terms of use', body: 'The terms covering use of this website, plans and billing, the 30-day money-back guarantee, ownership of the workflows we build, and the limits of what PerceptFolio provides.' }, es: { section: 'Legal', title: 'Términos de uso', body: 'Los términos que cubren el uso de este sitio, planes y facturación, la garantía de devolución de 30 días, la propiedad de los flujos que construimos, y los límites de lo que ofrece PerceptFolio.' } },
  { url: 'privacy.html', en: { section: 'Legal', title: 'Privacy and your data', body: 'What this site stores in your browser, what happens to a message you send us, cookies and analytics, and how to delete everything held on your device.' }, es: { section: 'Legal', title: 'Privacidad y tus datos', body: 'Qué guarda este sitio en tu navegador, qué pasa con un mensaje que nos envías, cookies y analítica, y cómo borrar todo lo guardado en tu dispositivo.' } }
];
